import { jsPDF } from "jspdf";

/**
 * PDF, CSV & Text Export Utilities
 */

export function generatePDFReport({ institution, regulation, programme, semester, gpaResult, cgpaResult, percentageResult, classificationResult, courses }) {
  const doc = new jsPDF();
  const primaryColor = "#0f172a";
  const accentColor = "#4f46e5";

  // Header Banner
  doc.setFillColor(15, 23, 42); // dark navy
  doc.rect(0, 0, 210, 38, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("MSEC & ANNA UNIVERSITY ACADEMIC TRANSCRIPT", 14, 18);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Institution: ${institution.institutionFullName || institution.institution} | Regulation: ${regulation.regulation}`, 14, 28);
  doc.text(`Generated: ${new Date().toLocaleDateString()} | Local Confidential Report`, 14, 34);

  // Metadata Block
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("STUDENT PROGRAMME & SEMESTER SUMMARY", 14, 48);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Programme: ${programme.name}`, 14, 56);
  doc.text(`Selected Semester: ${semester.label} (Semester ${semester.number})`, 14, 62);
  doc.text(`System: ${regulation.academicSystem}`, 14, 68);

  // Results Dashboard Box
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, 75, 182, 32, 3, 3, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(79, 70, 229);
  doc.text(`GPA: ${gpaResult.gpaFormatted}`, 22, 90);
  doc.text(`CGPA: ${cgpaResult.cgpaFormatted}`, 72, 90);
  doc.text(`Percentage: ${percentageResult.percentageFormatted}`, 122, 90);

  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text(`Classification: ${classificationResult.label}`, 22, 100);
  doc.text(`Credits Registered: ${gpaResult.totalCreditsRegistered}`, 122, 100);

  // Table Headers
  let y = 118;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setFillColor(226, 232, 240);
  doc.rect(14, y - 6, 182, 9, "F");

  doc.text("Code", 16, y);
  doc.text("Course Title", 42, y);
  doc.text("Type", 125, y);
  doc.text("Credit", 155, y);
  doc.text("Grade", 175, y);
  doc.text("C × GP", 192, y, { align: "right" });

  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);

  gpaResult.breakdown.forEach((item) => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    const title = item.name.length > 40 ? item.name.substring(0, 37) + "..." : item.name;
    doc.text(item.code || "-", 16, y);
    doc.text(title, 42, y);
    doc.text(item.type || "Theory", 125, y);
    doc.text(String(item.credits), 158, y);
    doc.text(item.grade || "-", 177, y);
    doc.text(String(item.pointsEarned || 0), 192, y, { align: "right" });
    y += 7;
  });

  // Footer Disclaimer
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("Disclaimer: Generated by MSEC & Anna University GPA Calculator for student self-assessment.", 14, 285);
  doc.text("Official records are governed by MSEC Controller of Examinations & Anna University gazette.", 14, 289);

  doc.save(`Academic_Report_${programme.shortName}_Sem${semester.number}.pdf`);
}

export function exportToCSV(gpaResult, programme, semester) {
  let csv = "Course Code,Course Name,Course Type,Credits,Grade,Grade Point,Credit Points (C x GP),Status\n";
  
  gpaResult.breakdown.forEach((item) => {
    const name = `"${(item.name || "").replace(/"/g, '""')}"`;
    csv += `${item.code},${name},${item.type},${item.credits},${item.grade || ""},${item.gradePoint !== null ? item.gradePoint : ""},${item.pointsEarned},${item.status}\n`;
  });

  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute("download", `Grades_${programme.shortName}_Sem${semester.number}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function generateTextSummary({ institution, regulation, programme, semester, gpaResult, cgpaResult, percentageResult, classificationResult }) {
  return `🎓 *MSEC & ANNA UNIVERSITY GPA SUMMARY*
---------------------------------------
📍 *Institution:* ${institution.institutionFullName || institution.institution}
📜 *Regulation:* ${regulation.regulation}
📚 *Programme:* ${programme.name}
🗓️ *Semester:* ${semester.label}

📊 *RESULTS:*
• *Semester GPA:* ${gpaResult.gpaFormatted}
• *Cumulative CGPA:* ${cgpaResult.cgpaFormatted}
• *Equivalent Percentage:* ${percentageResult.percentageFormatted}
• *Academic Class:* ${classificationResult.label}
• *Credits Earned:* ${gpaResult.totalCreditsEarned} / ${gpaResult.totalCreditsRegistered}

🔒 *Calculated via MSEC GPA & CGPA Calculator*`;
}
